services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: greenhouse-mosquitto
    ports:
      - "1884:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
  nodered:
    image: nodered/node-red:latest
    dns:
      - 8.8.8.8
      - 8.8.4.4
    container_name: greenhouse-nodered
    ports:
      - "1881:1880"
    volumes:
      - ./nodered/data:/data
    restart: unless-stopped
    depends_on:
      - mosquitto
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: greenhouse-homeassistant
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8123:8123"
    restart: unless-stopped
    depends_on:
      - mosquitto
      - nodered